#!/bin/bash

homefolder="$HOME/Dropbox/taskfolder"
execfolder="/usr/bin/"

if [[ -e task && -e tasks ]];then
	if [[ -d $HOME/Dropbox  ]]; then	
		if [[ -d  $HOME/Dropbox/taskfolder ]]; then
			echo "ok"
			else echo "[Info ]    Creating folder"
			mkdir $HOME/Dropbox/taskfolder
			echo "[Info ]    ............... [OK]"
		fi
		else echo "[Error]    Install DROPBOX first to '$HOME/Dropbox' "
		exit
	fi
	else echo "You havn't got any files to install"
	exit
fi

cp tasks $homefolder
echo "[Info ]    Coping files......[OK]"
chmod +x task
sudo cp task $execfolder
echo "CONGRATULATION!!! Now you can use this application!"
echo "Installation successfull!"
